### ISSUE TITLE
Showing up as the smaller cpp_boilerplate_project

### ISSUE THREAD

**Issue by viniciusferrao** [cpp-best-practices/cpp_starter_project#202]
I don't know what happened but the last commits removed a lot of files from the starter project and looks exactly like `cpp_boilerplate_project` now. On [README.md](https://github.com/cpp-best-practices/cpp_starter_project/blob/main/README.md) it links itself's as "a more complex example project, check out the [cpp_starter_project](https://github.com/cpp-best-practices/cpp_starter_project)."

Am I missing something or the repo is broken?

Thank you.

**Comment by lefticus** [comment]
I have updated the readme with #203 

I did remove many sub projects, yes, because they were all commented out and not ever checked (and were likely broken) I'm going to add back in some, but also we are creating more diverse standalone example templates, see also: https://github.com/cpp-best-practices/ftxui_template
